### ISSUE TITLE
A word about copyright, licensing and credit

### ISSUE THREAD

**Issue by inventor02** [TCDG/SSL-Community-Website#1]
The ScammerSubLounge.com website does not have a license. Therefore, you are infringing upon my copyright (I wrote 95% of that website) by hosting a copy of the SSL.com code on a public repository. What's more, I received no named credit whatsoever. How can TCDG call itself "open source" and "fair" when they infringe upon the copyright of others? That's not how it works.

I'm not getting all powerhungry here, but it pisses me off when someone steals **my** work and gives me no credit. If you're not willing to give proper credit and atleast ask me whether I'd like it hosted, I have no interest in being part of SSL projects and will file a DMCA takedown request.

**Comment by inventor02** [comment]
(and whoever's changed it fucked up the moderation page and the image in the header is squashed)

**Comment by justinoboyle** [comment]
[https://banne.me](https://banne.me) @XeliteXirish

**Comment by realshaunoneill** [comment]
We're redesigning the whole site, the current version is just while we're working on it @inventor02 Sorry if it upset you, I just threw it up until we're done. Sorry
