### ISSUE TITLE
I haveing ishu with website. I cant not find the exe file to run.

### ISSUE THREAD

**Issue by ghost** [TCDG/SSL-Community-Website#14]
Hi guys I am my name is Syskey and I had problem with ur website. I cant run and u forgot to put .exe file in your website so I cant not run it. Also i tryd to running the js file and it says no program is comptatible with the js file. Please fix asap thanks

**Comment by realshaunoneill** [comment]
Please explain exactly what you are having trouble with.  This doesn't make any sense

**Comment by inventor02** [comment]
It's a website - you don't run it.

Install Apache or nginx or a decent webserver and serve the files. If you don't know how to do that you shouldn't be running a website.

**Comment by IDevJoe** [comment]
You do not belong on GitHub if you do not know how to serve files.

**Comment by Kelwing** [comment]
Man you guys got trolled by Syskey so hard.
