### ISSUE TITLE
Your privacy policy is nonexistant

### ISSUE THREAD

**Issue by inventor02** [TCDG/SSL-Community-Website#29]
sslcommunity.io/privacy doesn't actually exist. Last time I checked that's not a good thing.

Have fun
<3 George

**Comment by Kelwing** [comment]
It's also pretty irrelevant on a static site that collects no user data,
and stores no cookies.

**Comment by inventor02** [comment]
what about all the other sites that do collect info and store cookies

**Comment by Kelwing** [comment]
They should probably have one in them instead of only on the homepage

**Comment by inventor02** [comment]
+1
