### ISSUE TITLE
[Project] Rewrite

### ISSUE THREAD

**Issue by inventor02** [TCDG/SSL-Community-Website#4]
Seeing as it's kinda my job to do the website for SSL I'll be rewriting the entire site, but with some nice blog features.

# Things that will be added
- [ ] Homepage
- [ ] Blog page

# Things that will be removed
- [ ] Moderation page (it's too much effort to maintain and I don't think anyone actually clicks on it)

It'll be written in Laravel in a new repository (as much as I love TCDG, not everything related to SSL has to be a TCDG project). If you'd like to help, get in touch.

**Comment by realshaunoneill** [comment]
Your welcome to rewrite the site etc, but we're not running it off a private users repository.  Its just safer to run it off a group were multiple people have control.

**Comment by inventor02** [comment]
@XeliteXirish It's on the SSL GitLab at https://git.sslcommunity.io.

**Comment by danielgraycode** [comment]
Can Daniel have a nice account for ssl gitlab please thanks.
